name: Test Wheel packaging

on: ["push", "pull_request"]

env:
  CMEEL_LOG_LEVEL: 'DEBUG'

jobs:
  build:
    name: "Build python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}-latest"
    strategy:
      matrix:
        os: ["ubuntu", "macos"]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup
        run: |
          python -m pip install -U pip
          python -m pip install wheel
      - name: build cmeel wheel
        run: python -m pip wheel -vw wh .
      - uses: actions/upload-artifact@v4
        with:
          name: "artifact-${{ matrix.os }}-${{ matrix.python-version }}"
          path: wh/example_adder-*.whl

  test:
    needs: ["build"]
    name: "Test ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}-latest"
    strategy:
      matrix:
        os: ["ubuntu", "macos"]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/download-artifact@v4
      - run: mkdir dist && mv artifact*/* dist
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup
        run: |
          python -m pip install -U pip
          python -m pip install wheel simple503
          python -m simple503 --sort --base-url "${GITHUB_WORKSPACE}/dist" dist
      - name: install wheel
        run: python -m pip install -i "file:///${GITHUB_WORKSPACE}/dist" --extra-index-url https://pypi.org/simple example-adder
      - name: test
        run: >
          python -c "import example_adder;
          assert example_adder.add(1, 2) == 3"
        env:
          PYTHONWARNINGS: error
